### ISSUE TITLE
File name with single quote gets lost in php connector

### ISSUE THREAD

**Issue by stueja** [jqueryfiletree/jqueryfiletree#53]
Hi,

I noticed that files with single quotes / apostrophes were not working.
Inspecting such an element in Google Chrome:

```html
<a rel="/mp3/Music For Cats/01 - David Teie - Lolo" s="" air.mp3'="">01 - David Teie - Lolo's Air.mp3</a>
```
That would pass the non-existing file `/mp3/Music For Cats/01 - David Teie - Lolo` on.

As for the php connector, the solution for me was to change `jQueryFileTree.php` from

```php
$htmlRel	= htmlentities($returnDir . $file);
```

to

```php
$htmlRel	= htmlentities($returnDir . $file,ENT_QUOTES);
```

Inspecting in Google Chrome now:

```html
<a rel="/mp3/Music For Cats/01 - David Teie - Lolo's Air.mp3">01 - David Teie - Lolo's Air.mp3</a>
```

Maybe worth a pull request, but my github knowledge is too limited to create one now.

Best Regards,
Jan

**Comment by daverogers** [comment]
I would accept that pull request if you made it. I use [Github Desktop](https://desktop.github.com/) because it's pretty simple for this kind of stuff. [This guide](https://guides.github.com/activities/contributing-to-open-source/) might help get you started on how the process works; essentially you just clone this project to your own github account, open that repo locally via your Git client (e.g. Github Desktop), make a branch called something like "encode quotes bug" (best practice), modify the code, and then send a pull request to this repo.

**Comment by stueja** [comment]
Hey Dave,
thanks alot for the hints. I (hopefully successfully) created my first-ever pull request #54 :)
Best Regards,
Jan

**Comment by daverogers** [comment]
thanks 👍 congrats on the pr 😃
